import Nav from "../components/Nav";
import CTAFooter from "../components/CTAFooter";

export const metadata = {
  title: "Terms of Service — Yoinky",
  description: "The terms that govern your use of the Yoinky desktop application.",
};

const PINK = "#F85BA9";
const DM = "DM Sans, sans-serif";

const S = {
  page:    { backgroundColor: "#FDF6EF", minHeight: "100vh" } as React.CSSProperties,
  wrap:    { maxWidth: 720, margin: "0 auto", padding: "clamp(72px,12vw,108px) clamp(24px,6vw,40px) clamp(64px,10vw,96px)" } as React.CSSProperties,
  tag:     { fontSize: 11, fontFamily: DM, fontWeight: 600, letterSpacing: "0.1em", color: PINK, textTransform: "uppercase" as const },
  h1:      { fontSize: "clamp(32px,6vw,52px)", fontWeight: 700, color: "#0C0C0C", lineHeight: 1.1, margin: "10px 0 14px", letterSpacing: "-0.5px" } as React.CSSProperties,
  meta:    { fontSize: 13, fontFamily: DM, color: "rgba(0,0,0,0.38)", marginBottom: 0 } as React.CSSProperties,
  divider: { border: "none", borderTop: "1px solid rgba(0,0,0,0.07)", margin: "clamp(32px,5vw,48px) 0" } as React.CSSProperties,
  h2:      { fontSize: "clamp(16px,2.8vw,19px)", fontWeight: 650, color: "#0C0C0C", letterSpacing: "-0.2px", margin: "clamp(32px,5vw,44px) 0 10px" } as React.CSSProperties,
  h3:      { fontSize: "clamp(13px,2vw,14px)", fontWeight: 600, color: "#222", letterSpacing: "0.01em", margin: "20px 0 6px" } as React.CSSProperties,
  p:       { fontFamily: DM, fontSize: "clamp(14px,2.4vw,15.5px)", color: "rgba(0,0,0,0.65)", lineHeight: 1.85, margin: "0 0 14px" } as React.CSSProperties,
  ul:      { fontFamily: DM, fontSize: "clamp(14px,2.4vw,15.5px)", color: "rgba(0,0,0,0.65)", lineHeight: 1.85, paddingLeft: 22, margin: "0 0 14px" } as React.CSSProperties,
  ol:      { fontFamily: DM, fontSize: "clamp(14px,2.4vw,15.5px)", color: "rgba(0,0,0,0.65)", lineHeight: 1.85, paddingLeft: 22, margin: "0 0 14px" } as React.CSSProperties,
  li:      { marginBottom: 8 } as React.CSSProperties,
  strong:  { color: "rgba(0,0,0,0.78)", fontWeight: 600 } as React.CSSProperties,
  warn:    { background: "#FFF0F7", border: `1px solid ${PINK}30`, borderRadius: 10, padding: "14px 18px", margin: "16px 0 20px", fontFamily: DM, fontSize: 14, color: "rgba(0,0,0,0.65)", lineHeight: 1.7 } as React.CSSProperties,
  note:    { background: "#F9F9FB", border: "1px solid rgba(0,0,0,0.07)", borderRadius: 10, padding: "14px 18px", margin: "16px 0 20px", fontFamily: DM, fontSize: 14, color: "rgba(0,0,0,0.6)", lineHeight: 1.7 } as React.CSSProperties,
  caps:    { fontFamily: DM, fontSize: "clamp(13px,2.2vw,14px)", color: "rgba(0,0,0,0.6)", lineHeight: 1.8, margin: "0 0 14px" } as React.CSSProperties,
};

export default function TermsPage() {
  return (
    <div style={S.page}>
      <Nav light />
      <main style={S.wrap} className="legal-body">

        {/* Header */}
        <p style={S.tag}>Legal</p>
        <h1 style={S.h1}>Terms of Service</h1>
        <p style={S.meta}>Effective: 19 June 2026 &nbsp;·&nbsp; Last updated: 19 June 2026</p>
        <hr style={S.divider} />

        {/* Beta callout */}
        <div style={S.warn}>
          <strong style={{ ...S.strong, color: PINK }}>Beta Software Notice</strong><br />
          Yoinky is currently in private beta. The Service is provided as an early, pre-release product that may contain bugs, incomplete features, and behaviour that changes without notice. By using Yoinky you acknowledge and accept the inherent instability of beta software, including the risk of data loss or unexpected behaviour.
        </div>

        {/* Intro */}
        <p style={S.p}>
          These Terms of Service ("Terms") govern your access to and use of the Yoinky desktop application and all related services (the "Service") operated by <strong style={S.strong}>Giksn Research</strong> ("we," "us," or "our"). By downloading, installing, or using the Service you agree to be bound by these Terms and our <a href="/privacy" style={{ color: PINK, textDecoration: "none" }}>Privacy Policy</a>, which is incorporated by reference.
        </p>
        <p style={S.p}>
          If you do not agree to these Terms, do not install or use the Service.
        </p>

        {/* 1 */}
        <h2 style={S.h2}>1. What Yoinky Does</h2>
        <p style={S.p}>
          Yoinky is a macOS desktop application that runs passively in the background, observes your application activity with your permission, builds a contextual memory layer from that activity, and uses it to restore cross-session context, surface relevant information proactively, and suggest personalised workflow automations.
        </p>
        <p style={S.p}>
          Suggestions and automations generated by Yoinky are based on patterns in your own activity data. They are informational in nature and do <strong style={S.strong}>not</strong> constitute professional, legal, financial, medical, or any other form of regulated advice. You remain solely responsible for every decision you make.
        </p>

        {/* 2 */}
        <h2 style={S.h2}>2. Who Can Use Yoinky</h2>
        <p style={S.p}>
          You must be at least <strong style={S.strong}>16 years of age</strong> to use the Service. By agreeing to these Terms, you represent that you meet this requirement. If you are using Yoinky on behalf of an organisation, you represent and warrant that you have full authority to bind that organisation to these Terms.
        </p>
        <p style={S.p}>
          Access during the beta period is by invitation only. We reserve the right to accept, decline, or revoke access at our sole discretion, at any time, without obligation to provide a reason.
        </p>

        {/* 3 */}
        <h2 style={S.h2}>3. Beta Program</h2>
        <ul style={S.ul}>
          <li style={S.li}>Features, pricing structures, availability, and data handling practices may change at any time during the beta without prior notice.</li>
          <li style={S.li}>We may terminate the beta program, or any individual's access to it, at any time with or without cause.</li>
          <li style={S.li}>Beta access is free unless we explicitly communicate otherwise in writing. The absence of a charge during beta does not create an entitlement to future free access.</li>
          <li style={S.li}>Feedback you provide during beta (bug reports, feature requests, suggestions) may be used to improve the product. You grant us a perpetual, irrevocable, worldwide, royalty-free licence to use such feedback in any manner without any obligation or compensation to you.</li>
          <li style={S.li}>We will make reasonable efforts to preserve your data across beta updates, but we cannot guarantee continuity and recommend maintaining your own backups for critical information.</li>
        </ul>

        {/* 4 */}
        <h2 style={S.h2}>4. Your Account</h2>
        <ul style={S.ul}>
          <li style={S.li}>You are responsible for maintaining the confidentiality of any credentials associated with your account.</li>
          <li style={S.li}>You must notify us immediately at <a href="mailto:parry@meetyoinky.com" style={{ color: PINK, textDecoration: "none" }}>parry@meetyoinky.com</a> if you suspect any unauthorised access to your account.</li>
          <li style={S.li}>You are responsible for all activity that occurs under your account.</li>
          <li style={S.li}>Each account is for a single individual. Account sharing or transferring access to another person is not permitted.</li>
        </ul>

        {/* 5 */}
        <h2 style={S.h2}>5. Acceptable Use</h2>
        <p style={S.p}>You agree to use Yoinky only for lawful purposes and in accordance with these Terms. You must not:</p>
        <ul style={S.ul}>
          <li style={S.li}><strong style={S.strong}>Monitor other people.</strong> Yoinky is a personal productivity tool. You may not install or use it to capture, monitor, or surveil the activity of any other person — including employees, contractors, family members, or any third party — without their explicit, fully-informed, and freely-given consent. Doing so may violate computer access laws, employment laws, and privacy regulations in your jurisdiction.</li>
          <li style={S.li}><strong style={S.strong}>Reverse engineer the app.</strong> You must not decompile, disassemble, reverse engineer, or attempt to extract the source code of the Yoinky application or any component of the Service.</li>
          <li style={S.li}><strong style={S.strong}>Circumvent security measures.</strong> You must not attempt to bypass, disable, or interfere with security mechanisms, rate limits, or access controls in the Service.</li>
          <li style={S.li}><strong style={S.strong}>Use automated access.</strong> You must not use bots, scrapers, or automated scripts to interact with the Service in ways not expressly permitted or intended.</li>
          <li style={S.li}><strong style={S.strong}>Introduce malicious code.</strong> You must not upload or transmit viruses, malware, or any code intended to damage, disrupt, or gain unauthorised access to systems.</li>
          <li style={S.li}><strong style={S.strong}>Infringe intellectual property.</strong> You must not use the Service in a way that infringes the intellectual property rights of Giksn Research or any third party.</li>
          <li style={S.li}><strong style={S.strong}>Resell or sublicence.</strong> You must not resell, sublicence, or commercially exploit the Service without our prior written consent.</li>
          <li style={S.li}><strong style={S.strong}>Violate applicable law.</strong> You must not use the Service for any purpose that is illegal under the laws of your jurisdiction or any applicable jurisdiction.</li>
        </ul>
        <p style={S.p}>
          We reserve the right to suspend or permanently terminate accounts that violate this section, without refund of any amounts paid.
        </p>

        {/* 6 */}
        <h2 style={S.h2}>6. Your Data and Our Licence to Process It</h2>
        <ul style={S.ul}>
          <li style={S.li}>You retain full ownership of the data you create, the content you work on, and the memories stored in your account. We do not claim ownership of your personal data.</li>
          <li style={S.li}>By using the Service you grant Giksn Research a limited, non-exclusive, worldwide licence to process your data solely for the purpose of providing and improving the Service, as described in the Privacy Policy.</li>
          <li style={S.li}>You are responsible for ensuring that your use of Yoinky — including connecting it to workplace tools — complies with any obligations you have to your employer, clients, or applicable law regarding monitoring, confidentiality, or data handling.</li>
          <li style={S.li}>We will never sell your personal data to third parties.</li>
        </ul>

        {/* 7 */}
        <h2 style={S.h2}>7. Third-Party Tools and Integrations</h2>
        <ul style={S.ul}>
          <li style={S.li}>Yoinky can integrate with third-party services such as Notion, Figma, Slack, Linear, and others. Your use of those services is subject entirely to their own terms of service and privacy policies.</li>
          <li style={S.li}>We are not responsible for the availability, accuracy, security, or conduct of any third-party service.</li>
          <li style={S.li}>Connecting a third-party tool to Yoinky is at your own risk. We recommend reviewing the permissions requested before authorising any integration.</li>
          <li style={S.li}>If a third-party service modifies or discontinues its API, the corresponding Yoinky integration may stop working. We will not be liable for any loss or inconvenience resulting from such changes.</li>
        </ul>

        {/* 8 */}
        <h2 style={S.h2}>8. Intellectual Property</h2>
        <ul style={S.ul}>
          <li style={S.li}>The Yoinky application, including its software, design, user interface, algorithms, documentation, and branding, is owned by Giksn Research and is protected by copyright, trade secret, and other applicable intellectual property laws.</li>
          <li style={S.li}>These Terms do not grant you any rights to our trademarks, logos, or brand assets. You must not use them without prior written permission.</li>
          <li style={S.li}>The structure, processing logic, and systems that organise and display your data are proprietary to Giksn Research. Your personal data and memory entries are yours — our code and algorithms are ours.</li>
          <li style={S.li}>You must not reproduce, distribute, modify, or create derivative works from any part of the Service without explicit written authorisation from Giksn Research.</li>
        </ul>

        {/* 9 */}
        <h2 style={S.h2}>9. Disclaimer of Warranties</h2>
        <p style={S.caps}>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, HASHIRA WORKS EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
        </p>
        <p style={S.caps}>
          WE DO NOT WARRANT THAT: (A) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (B) RESULTS OBTAINED THROUGH THE SERVICE WILL BE ACCURATE, RELIABLE, OR MEET YOUR REQUIREMENTS; (C) DEFECTS IN THE SERVICE WILL BE CORRECTED; OR (D) THE SERVICE OR THE SERVERS THAT MAKE IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
        </p>
        <p style={S.caps}>
          AS BETA SOFTWARE, YOU SPECIFICALLY ACKNOWLEDGE THAT DISRUPTIONS, DATA LOSS, FEATURE REMOVAL, AND UNEXPECTED BEHAVIOUR ARE INHERENT RISKS OF PARTICIPATION IN THE BETA PROGRAM.
        </p>

        {/* 10 */}
        <h2 style={S.h2}>10. Limitation of Liability</h2>
        <p style={S.caps}>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL HASHIRA WORKS, ITS OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE, OR ANY COMMERCIAL LOSS, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR YOUR USE OF, OR INABILITY TO USE, THE SERVICE — EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </p>
        <p style={S.caps}>
          OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNTS PAID BY YOU TO HASHIRA WORKS IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM; OR (B) USD $100.
        </p>
        <p style={S.p}>
          Some jurisdictions do not allow the exclusion or limitation of certain damages. In such jurisdictions our liability is limited to the maximum extent permitted by law. Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, fraud, or fraudulent misrepresentation, or any other liability that cannot be excluded or limited by applicable law.
        </p>

        {/* 11 */}
        <h2 style={S.h2}>11. Indemnification</h2>
        <p style={S.p}>
          You agree to indemnify, defend (at our option), and hold harmless Giksn Research and its affiliates, officers, directors, employees, and agents from and against any third-party claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to: (a) your use of the Service in violation of these Terms; (b) your violation of any applicable law or regulation; (c) your infringement of any third party's intellectual property or other rights; or (d) any data you submit to or through the Service.
        </p>

        {/* 12 */}
        <h2 style={S.h2}>12. Termination</h2>

        <h3 style={S.h3}>12.1 By you</h3>
        <p style={S.p}>
          You may stop using the Service at any time. To delete your account and all associated data, go to <strong style={S.strong}>Settings → Delete Account</strong> within the app, or contact us at <a href="mailto:parry@meetyoinky.com" style={{ color: PINK, textDecoration: "none" }}>parry@meetyoinky.com</a>. We will process deletion requests within 30 days.
        </p>

        <h3 style={S.h3}>12.2 By us</h3>
        <p style={S.p}>
          We may suspend or permanently terminate your access to the Service at any time, with or without cause, with or without prior notice. Reasons may include, but are not limited to: breach of these Terms, conduct that harms other users or third parties, legal or regulatory requirements, or the discontinuation of the beta program or the Service itself.
        </p>

        <h3 style={S.h3}>12.3 Effect of termination</h3>
        <p style={S.p}>
          Upon termination, your right to use the Service ceases immediately. Sections 8, 9, 10, 11, 13, and 14 of these Terms survive termination. We will retain your data only for the period required by law before deleting it in accordance with our Privacy Policy.
        </p>

        {/* 13 */}
        <h2 style={S.h2}>13. Governing Law and Disputes</h2>
        <p style={S.p}>
          These Terms are governed by and construed in accordance with the laws of India, without regard to its conflict-of-law provisions. Any dispute, controversy, or claim arising out of or in connection with these Terms, including questions of their existence, validity, or termination, shall first be attempted to be resolved through good-faith negotiation between the parties.
        </p>
        <p style={S.p}>
          If the dispute cannot be resolved through negotiation within 30 days, it shall be finally settled by binding arbitration in Bengaluru, India, conducted in English and in accordance with the Arbitration and Conciliation Act, 1996. Judgement upon the arbitral award may be entered in any court of competent jurisdiction.
        </p>
        <p style={S.p}>
          <strong style={S.strong}>Class action waiver:</strong> You agree that any proceedings to resolve disputes will be conducted on an individual basis and not as part of a class, consolidated, or representative action.
        </p>
        <p style={S.p}>
          Nothing in this section prevents either party from seeking urgent or interim injunctive relief from a court of competent jurisdiction to prevent irreparable harm.
        </p>

        {/* 14 */}
        <h2 style={S.h2}>14. General Provisions</h2>
        <ul style={S.ul}>
          <li style={S.li}><strong style={S.strong}>Entire agreement.</strong> These Terms, together with the Privacy Policy, constitute the entire agreement between you and Giksn Research regarding the Service and supersede all prior understandings.</li>
          <li style={S.li}><strong style={S.strong}>Severability.</strong> If any provision of these Terms is found to be invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the remaining provisions will remain in full force.</li>
          <li style={S.li}><strong style={S.strong}>No waiver.</strong> Our failure to enforce any right or provision of these Terms will not constitute a waiver of that right or provision.</li>
          <li style={S.li}><strong style={S.strong}>Assignment.</strong> You may not assign or transfer these Terms without our prior written consent. We may assign these Terms freely, including in connection with a merger, acquisition, or sale of assets, with notice to you.</li>
          <li style={S.li}><strong style={S.strong}>No agency.</strong> These Terms do not create any partnership, joint venture, employment, or agency relationship between you and Giksn Research.</li>
          <li style={S.li}><strong style={S.strong}>Force majeure.</strong> Neither party will be liable for failure or delay in performance caused by circumstances beyond their reasonable control, including natural disasters, government actions, or widespread internet disruptions.</li>
          <li style={S.li}><strong style={S.strong}>Language.</strong> These Terms are written in English. In the event of a translation being provided for convenience, the English version will govern in case of conflict.</li>
        </ul>

        {/* 15 */}
        <h2 style={S.h2}>15. Changes to These Terms</h2>
        <p style={S.p}>
          We may update these Terms from time to time. For material changes — those that meaningfully affect your rights or obligations — we will provide at least 14 days' notice by email or prominent in-app notification before the changes take effect. Your continued use of the Service after that date constitutes acceptance of the revised Terms. If you do not agree to the updated Terms, you must stop using the Service before they take effect.
        </p>

        {/* 16 */}
        <h2 style={S.h2}>16. Contact</h2>
        <p style={S.p}>For questions about these Terms or the Service:</p>
        <div style={S.note}>
          <strong style={S.strong}>Giksn Research</strong> (operating Yoinky)<br />
          Email: <a href="mailto:parry@meetyoinky.com" style={{ color: PINK, textDecoration: "none" }}>parry@meetyoinky.com</a><br />
          Subject line: "Terms Query — [your name]"
        </div>

      </main>
      <CTAFooter />
    </div>
  );
}
